package com.example.triptuneletter.category.travel

enum class Country(val description: String) {
    KOREA("대한민국"),
    JAPAN("일본"),
    CHINA("중국"),
    HONG_KONG("홍콩"),
    MACAU("마카오"),
    VIETNAM("베트남"),
    THAILAND("태국"),
    TAIWAN("대만"),
    SINGAPORE("싱가포르"),
    PHILIPPINES("필리핀"),
    MALAYSIA("말레이시아"),
    INDONESIA("인도네시아"),
    USA("미국"),
    CANADA("캐나다"),
    FRANCE("프랑스"),
    UK("영국"),
    ITALY("이탈리아"),
    SPAIN("스페인"),
    GERMANY("독일"),
    SWITZERLAND("스위스"),
    AUSTRIA("오스트리아"),
    CZECH("체코"),
    AUSTRALIA("호주"),
    NEW_ZEALAND("뉴질랜드"),
    PORTUGAL("포르투갈"),
    NETHERLANDS("네덜란드"),
    BELGIUM("벨기에"),
    GREECE("그리스"),
    TURKEY("터키"),
    EGYPT("이집트"),
    UAE("아랍에미리트"),
    MEXICO("멕시코"),
    BRAZIL("브라질"),
    ARGENTINA("아르헨티나"),
    OTHERS("기타")
}

