spring.application.name=backend

# MySQL 설정
spring.datasource.url=jdbc:mysql://localhost:3306/trip_tune?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=trip-tune-letter-dev-secret-012345
jwt.expiration-ms=86400000

logging.level.org.springframework.security=TRACE
server.error.include-message=always
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE